### ISSUE TITLE
[Tracker] Key features for PoC

### ISSUE THREAD

**Issue by debloper** [debloper/soapbox#1]
- **Routing**
  - [ ] Use history API to navigate between pages
  - [ ] Create routing table from YAML frontmatter
- **Build**
  - [ ] Convert **markdown** with **frontmatter** to JSON as part of build process
  - [ ] Copy markup, styles & scripts accordingly as part of build process
  - [ ] Use `make` as the primary build tool
- **Content**
  - [ ] Use `index.html` as page skeleton
  - [ ] Use converted JSON as page contents
- **Misc**
  - [ ] Keep the 3rd party dependencies to bare minimum
